### ISSUE TITLE
Flickering on wifi use

### ISSUE THREAD

**Issue by lostb1t** [liebman/esp-hub75#24]
So this is more of a general help question. Sorry of this is not the place.

Im running s project with this crate successfully. I have the display and hub75 on core 1.

The display is driven by data fetched by some http calls, this data is fetched by an task on core 0 and then communicate to the display task through a channel
My issue is that every time theres wifi/network activity my display flickers. Disabling the network calls fixes the flickering.

Wondering if anyone has some pointers on what might cause this

(esp32-s3)

**Comment by lostb1t** [comment]
using esp-println + log. Removing it doesnt seem to affect anything.

**Comment by lostb1t** [comment]
i could share the code if thats helpfull.

**Comment by liebman** [comment]
> i could share the code if thats helpfull.

please do

**Comment by lostb1t** [comment]
Project here: https://github.com/lostb1t/allaboard_emb

Codebase is pretty straightforward.

Every-time there's wifi activity theres flickering.

**Comment by liebman** [comment]
as an experiment, move the display task to core 0 and run the hub75 task in a normal executor with something like this:
```rust
        // run hub75 on second core
        let cpu1_fnctn = {
            move || {
                info!("main: starting executors on second core");

                let lp_executor = mk_static!(Executor, Executor::new());
                lp_executor.run(|spawner| {
                    spawner
                        .spawn(crate::hub75::run(display_peripherals, &RX, &TX, fb1))
                        .ok();
                });
            }
        };
```  

I have a matrix clock and it only updates the display once a second and thats how I have it set. I used to have it on core 1  and moved it, IIRC because of wifi interfering with the interrupt executor somehow.

**Comment by liebman** [comment]
maybe you can make a small reproducer based on the hello_lcd_cam example?

**Comment by lostb1t** [comment]
a test projector can be found here: https://github.com/lostb1t/flicker_test

WIFI_SSID="YOURSSID" WIFI_PWD="YOURPW" cargo run

they are not heavy payloads so flickering is light but still noticeable.

I am however running this from an Adafruit Matrix Portal S3 (clone) so you will need to redo the pins to match your board (s3)

**Comment by liebman** [comment]
Have you tried compiled with `--release`?  That seems to remove the flicker in my testing.
In any case I'll be adding a cargo feature that will move the rendering hot path into ram.
The underlying issue here is that the the rendering function get pushed out of the CACHE when wifi runs (its a fixed size cache of 32k I believe)

**Comment by lostb1t** [comment]
> Have you tried compiled with `--release`?  That seems to remove the flicker in my testing.
> In any case I'll be adding a cargo feature that will move the rendering hot path into ram.
> The underlying issue here is that the the rendering function get pushed out of the CACHE when wifi runs (its a fixed size cache of 32k I believe)

yes tried release, which did not help

looking forward to the feature.

**Comment by liebman** [comment]
I've merged the `iram` feature.

**Comment by lostb1t** [comment]
appreciated the help. unfortunately it did not fix my issue. So ill continue to research

**Comment by liebman** [comment]
You could also try modifying similar functions in the `esp-hal` lcd_cam `i8080` driver.

**Comment by lostb1t** [comment]
ill give it a shot tnx
